config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'static#landing'
  devise_for :users
  resources :blogs do
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :comments

  has_one_attached :image
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)
    @blog.user = current_user
    @blog.image.attach(params[:blog][:image])

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body, :image, :user_id)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<div class="container">
  <%= form_with(model: blog, local: true) do |form| %>
    <% if blog.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

        <ul>
        <% blog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :body %>
      <%= form.text_area :body, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :image %>
      <%= form.file_field :image, class: 'form-control' %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/blogs/edit.html.erb
<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>
<h1 class="text-center">Editing Blog</h1>

<%= render 'form', blog: @blog %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">Blogs</h1>

<div class="container">

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Title</th>
        <th>Body</th>
        <th>User</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @blogs.each do |blog| %>
        <tr>
          <td><%= blog.title %></td>
          <td><%= blog.body %></td>
          <td><%= blog.user.first_name %></td>
          <td><%= link_to 'Show', blog %></td>
          <% if user_signed_in? %>
            <% if blog.user_id == current_user.id %>
              <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
              <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/blogs/new.html.erb
<%= link_to 'Back', blogs_path %>
<h1 class="text-center">New Blog</h1>

<%= render 'form', blog: @blog %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>


<div class="container">
  <%= link_to 'Back', blogs_path, class: 'btn btn-primary my-4' %>
  <div class="card">
    <%= image_tag @blog.image, class: 'img-responsive', height: '300px', width: '300px' %>
    <div class="card-body">
      <h5 class="card-title"><%= @blog.title %></h5>
      <p class="card-text"><%= @blog.body %></p>
      <% if user_signed_in? %>
        <% if @blog.user_id == current_user.id %>
          <%= link_to 'Edit', edit_blog_path(@blog) %> |
          <%= link_to 'Delete', @blog, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      <% end %>
    </div>
  <div class="card-footer">
    <% @blog.comments.each do |comment| %>
    <li class="list-group-item">
      <% if user_signed_in? %>
        <% if comment.user_id == current_user.id %>
          <%= link_to edit_blog_comment_path(@blog, comment) do %>
            <%= comment.body %>
          <% end %>
        <% elsif !(comment.user_id == current_user.id) %>
          <%= comment.body %>
        <% end %>
      <% end %>
      <% if !user_signed_in? %>
        <%= comment.body %>
      <% end %>
      <br>
      Posted By:
      <%= comment.user.full_name %>
      <br>
    </li>
    <% end %>
    <br>
  </ul>

  <% if user_signed_in? %>
    <%= link_to 'Add A New Comment', new_blog_comment_path(@blog) %>
  <% end %>
  </div>
  </div>
</div>