config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'static#landing'
  devise_for :users
  resources :blogs do
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-light bg-light">
  <%= link_to 'Home', root_path, class: 'navbar-brand' %>

  <ul class="navbar-nav ml-auto">
    <li class="nav-item">
      <%= link_to 'Blogs', blogs_path, class: 'nav-link' %>
    </li>
    <% if user_signed_in? %>
    <li class="nav-item">
      <%= link_to 'New Blog', new_blog_path, class: 'nav-link' %>
    </li>
    <% end %>
  </ul>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <a class="nav-link">You are logged in as: <%= current_user.full_name %></a>
        </li>
        <li class="nav-item">
          <%= link_to 'Edit Profile', edit_user_registration_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% end %>
      <% if !user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Log In', new_user_session_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>